### PR TITLE
Provide IDs and speeds for some slow bridges

### PR DESCRIPTION
**Pull request by jbzdarkid**

### CODE REVIEW

**Comment by sigma144** [comment]
Thanks darkid! Do you happen to know how to speed up the boathouse ramp raising/sliding as well?

**Comment by jbzdarkid** [comment]
[List of Panel, EP, Audio Log, and Door IDs](https://docs.google.com/spreadsheets/d/13Qohr67j9bgDdazimJOCkpmq7avVDjrPwmbyGGfCdsI/edit#gid=1580020559)
Pretty sure it's
0x17C6A | Boathouse | Ramp Angle
-- | -- | --

**Comment by jbzdarkid** [comment]
@sigma144 any particular reason you ripped this out again?

**Comment by jbzdarkid** [comment]
OIC, merged into dev-1.2 instead of master.

**Pull request merged**
